name: 'MC_Arcade'
main: dev.theturkey.mcarcade.MCACore
description: 'Remaking various arcade and video games in Minecraft!'
version: ${projectVersion}
authors: [TurkeyDev]
depend: ['ProtocolLib']
api-version: '1.16'
load: POSTWORLD
commands:
  mcarcade:
    description: MC Arcade Commands